name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: nightly

    env:
      LANG: de_DE.UTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup ${{ matrix.rust}} toolchain
      run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          cargo --version
          rustup show

    - uses: Swatinem/rust-cache@v2

    - name: Test
      shell: bash
      run: |
        cargo test -- --nocapture
